<?php
/**
 * 评论控制器
 * User: wetist
 * Date: 2017/3/21
 * Time: 10:21
 */

namespace app\index\controller;


use think\Request;

class Comment extends Base
{
    public function _initialize($token_allow = [], $request = null)
    {
        $token_allow = [];//需要token验证的action,小写
        parent::_initialize($token_allow, $request); // TODO: Change the autogenerated stub
    }

    /**
     * 创建评论
     */
    function createComment()
    {
        $request = Request::instance();
        $data['uid'] = $request->param('uid', 0, 'intval') or data_format_json(-1, '', 'uid is null');
        $data['comment_id'] = $request->param('comment_id', 0, 'intval');
        $data['tale_id'] = $request->param('tale_id', 0, 'intval') or data_format_json(-1, '', 'tale_id is null');
        $data['content'] = $request->param('content', '') or data_format_json(-1, '', 'content is null');
        $service_comment = new \app\index\service\Comment();
        $service_comment->create_comment($data);
    }

}